services:
  server:
    container_name: "ts-dc-bot-dev"
    command: yarn dev
    build:
      context: .
      dockerfile: "./Dockerfile.dev"
    env_file:
      - .env
    # ports:
    #   - 8081:8081 
    volumes:
      - ./:/app
